apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: "external-vault"
      caFile: "/etc/ssl/certs/ca-certificates.crt"
      sni: "vault-cluster-public-vault-e1e94f3d.c53462dd.z1.hashicorp.cloud"